Rename and simplify update_about.py
The tool is now named colophon.py, because it manages the 'colophon' of
the project, the metadata, like in a book.

It now gets the output path from the pyproject.toml file, together with
the template for generating the colophon. It is still not fully generic
because it is using an extra metadata item that may be removed at some
point in the future.

The git hooks which used the tool have been modified.

diff --git a/tools/hooks/common b/tools/hooks/common
--- a/tools/hooks/common
+++ b/tools/hooks/common
@@ -5,9 +5,9 @@ die() {
     exit 1;
 }
 
-update_about() {
-    python tools/update_about.py || die 'The about.py file could not be generated.'
-    pip install -q -e . || die 'The editable install could not be updated.'
+update_colophon() {
+    COLOPHON_PATH=$(python tools/colophon.py) || die 'The colophon file could not be generated.'
+    # pip install -q -e . || die 'The editable install could not be updated.'
 }
 
 if [ -f .venv/Scripts/activate ]; then
